
project_id = "uwrmtukgjnsjxcojqmic"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions.get-admin-users]
verify_jwt = true

[functions.update-user-profile]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.activate-free-subscription]
enabled = true
verify_jwt = true
import_map = "./functions/activate-free-subscription/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/activate-free-subscription/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/activate-free-subscription/*.html" ]
